language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
install:
# command to install dependencies
  - "pip install coveralls"
  - "pip install pytz" # Needed for tests
  - pip install -q Django==$DJANGO
  - "pip install ."
# command to run tests
script:
  - coverage run --branch --source=notifications manage.py test
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7
after_success:
  - coveralls
